project:
  type: website
  output-dir: docs

# render only the contents mentioned in the _quarto.yml file


website: 
  title: "Vayu"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Introduction"
        path: "index.qmd"

      - section: "Examples"
        contents:
          - examples/calendar_plot.ipynb
          - examples/pollution_rose.ipynb

execute:
  freeze: auto